### ISSUE TITLE
Question..

### ISSUE THREAD

**Issue by jilabaca** [mettke/ssh-key-authority#21]
Hello, I would like to know if the project is really maintained or not? Since I have been looking for something similar and open-source, but I have not found anything, and since I have not seen activity in the project for quite some time, I wanted to know if it is 100% operational or it is not recommended to use it.

**Comment by mettke** [comment]
Hey @jilabaca, This is operational but as it is feature complete there are no changes anymore. 
Its not recommended to run this on the public internet because there is no patching policy for security issues.

If you want to run this, either make sure its well protected or you have to perform the patching yourself.

In general this software is 100% operational and works as expected.

**Comment by jilabaca** [comment]
Thanks @mettke for your comment!
